from reset_testdb import User, Location, Ranking, Song, db


user1 = User('admin', 'pass123')
user2 = User('Johnny', 'clever')
user3 = User('Susan', 'l0v3r')

loc1 = Location('Siebel Center', 'Urbana', 40.113803, -88.224905)
loc2 = Location('Grainger Library', 'Urbana', 40.112500, -88.226917)
loc3 = Location('Undergraduate Library', 'Urbana', 40.104704, -88.226841)
loc4 = Location('West Side Park', 'Champaign', 40.117351, -88.247944)

song1 = Song('Kalafina', 'Red Moon', 'Red Moon')
song2 = Song('Radiohead', 'Paranoid Android', 'OK Computer')
song3 = Song('Yiruma', 'Loanna', 'P.N.O.N.I')
song4 = Song('Deafheaven', 'Dream House', 'Sunbather')
song5 = Song('Nujabes', 'Counting Stars', 'Modal Scores')

r1 = Ranking(2, 5, 4)
r2 = Ranking(2, 4, 2)
r3 = Ranking(2, 1, -2)
r4 = Ranking(1, 3, 6)
r5 = Ranking(1, 2, 16)
r6 = Ranking(1, 4, 1)
r7 = Ranking(3, 4, 2)
r8 = Ranking(3, 5, 10)
r9 = Ranking(3, 3, -1)
r10 = Ranking(4, 1, 11)
r11 = Ranking(4, 4, 7)
r12 = Ranking(4, 3, 3)
r13 = Ranking(1, 1, 3)


db.session.add(user1)
db.session.commit()
db.session.add(user2)
db.session.commit()
db.session.add(user3)
db.session.commit()


db.session.add(loc1)
db.session.commit()
db.session.add(loc2)
db.session.commit()
db.session.add(loc3)
db.session.commit()
db.session.add(loc4)
db.session.commit()

db.session.add(song1)
db.session.commit()
db.session.add(song2)
db.session.commit()
db.session.add(song3)
db.session.commit()
db.session.add(song4)
db.session.commit()
db.session.add(song5)
db.session.commit()

db.session.add(r1)
db.session.commit()
db.session.add(r2)
db.session.commit()
db.session.add(r3)
db.session.commit()
db.session.add(r4)
db.session.commit()
db.session.add(r5)
db.session.commit()
db.session.add(r6)
db.session.commit()
db.session.add(r7)
db.session.commit()
db.session.add(r8)
db.session.commit()
db.session.add(r9)
db.session.commit()
db.session.add(r10)
db.session.commit()
db.session.add(r11)
db.session.commit()
db.session.add(r12)
db.session.commit()
db.session.add(r13)
db.session.commit()

